### ISSUE TITLE
ESLint config describing prettier's preferences?

### ISSUE THREAD

**Issue by silvenon** [prettier/eslint-config-prettier#10]
In Atom I want to display inline ESLint errors for stuff that will be corrected by prettier-eslint. I expected this config to be a set of ESLint rules describing prettier preferences, not disabling those rules. Am I missing something?

**Comment by lydell** [comment]
eslint-config-prettier is all about disabling rules. (If you come up with a better name, please tell me!)

I don't know of an eslint config that tries to mimic prettier.
