### ISSUE TITLE
Turn off lines-between-class-members

### ISSUE THREAD

**Issue by gpoitch** [prettier/eslint-config-prettier#101]
https://eslint.org/docs/rules/lines-between-class-members

Just noticed a bunch line breaks added when updating some other eslint plugins (standard) that recently added this rule.  I believe line breaks are a prettier concern?

**Comment by j-f1** [comment]
I believe Prettier allows either version, so it should be up to users whether or not to enable this rule.

**Comment by gpoitch** [comment]
You're correct, allows either. Thanks.
https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOO0cAFAJTFkUWM4C+LMA7hHQ+Uy3b8OACwBOcGvVL9m-IXIoAzCAFcxOALw5emgHzEFOJQEsAbnC076+wyxaYTADyu6DwIUJAAaEBAAOMCbQmMig6GJiEJwAChEIoSjoZhAmACY+IABGYuhgANZwMADK-nkmUADmyDBiqnC+IjAAtqgA6iIm8JhlYHDFCV3mXQCeyODYmRWYcGIwMbmVzejISuioM74AVphOAEK5BUXF6M1wADIVcKvrmyA7TsUVlahwAIqqEPA3Gw0gZWIZmJxll0Fk4KhMv4xBUYG10jARMgABwABl80IgMzauX842hcCBFkyAEdPvAFgFEiAsABaKCSNJwDK+CRkkwSBboJYrJBrX6+GbNEw1Op-RxVV4fL7XPm3P4wMHwtKI5AAJl8tXQJlQzwAwhBmstxlAqJlVDMACpgxL8masVhAA
