### ISSUE TITLE
New rule "@typescript-eslint/quotes"

### ISSUE THREAD

**Issue by ybiquitous** [prettier/eslint-config-prettier#104]
Hi, I noticed that the new rule `@typescript-eslint/quotes` has been added since `@typescript-eslint@2.1.0`:

- https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.1.0
- https://github.com/typescript-eslint/typescript-eslint/pull/762
- https://github.com/typescript-eslint/typescript-eslint/blob/v2.1.0/packages/eslint-plugin/docs/rules/quotes.md

I'm prepared for opening a new PR to add this new rule to the `@typescript-eslint.js`:

https://github.com/prettier/eslint-config-prettier/blob/793aa76f9045a1aa9237558c343e64e957b56984/%40typescript-eslint.js#L4-L11

But I'm not sure whether we should modify also the "quotes" section in README.
https://github.com/prettier/eslint-config-prettier/blob/v6.1.0/README.md#quotes

**Comment by lydell** [comment]
Hi!

I think we need to do the same as we did for `babel/quotes`.

https://github.com/prettier/eslint-config-prettier#quotes

> (The following applies to babel/quotes as well.)

I think all that needs to be done is:

- Update the plugin.
- Update the version of the plugin in the readme.
- Add the note to the Quotes section.
- Add the rule as a special rule.

**Comment by ybiquitous** [comment]
Thank you! I will try it. 💪

**Comment by ybiquitous** [comment]
I opened the new PR #105. I would be happy if I could receive reviews. 😃
