### ISSUE TITLE
the rule ‘function-paren-newline’ is not effect？

### ISSUE THREAD

**Issue by dale426** [prettier/eslint-config-prettier#106]
on my project have a file that name is  .prettier;
i write the content: 
```shell
{
  "singleQuote": true,
  "rules": {
    "function-paren-newline": "off"
  }
}
```
but, the param code have a new line  when i use the prettier formater my code;
example: 
```js
before:
this.$tow.open(this.$funHandler("order-car-input-reason", {}, {orderCode: this.orderCode}));

// after  use prettier formater;
this.$tow.open(
    this.$funHandler(
        'order-car-input-reason',
        {},
        { orderCode: this.orderCode }
    )
);
```
now the 'singleQuote' is effect ;
expect  'function-paren-newline' is never;

**Comment by j-f1** [comment]
We don’t support rules like that, unfortunately. You have to use the style Prettier suggests.
