### ISSUE TITLE
Rule conflict: indent 💥 prettier

### ISSUE THREAD

**Issue by rasenplanscher** [prettier/eslint-config-prettier#108]
Using `--fix` with `'prettier/prettier': 'error'` and `'@typescript-eslint/indent': ['error', 2]`, I get this transformation:
```node
spawn(
	'executable',
	['argument1', 'argument2'],
	{ stdio: ['inherit', 'pipe', 'inherit'] },
)
```
⬇
```node
spawn('executable', ['argument1', 'argument2'], {
  { stdio: ['inherit', 'pipe', 'inherit'] },
});
```

Happens with the latest versions of all packages involved:
```json
    "@typescript-eslint/eslint-plugin": "^2.2.0",
    "@typescript-eslint/parser": "^2.2.0",
    "@typescript-eslint/typescript-estree": "^2.2.0",
    "eslint": "^6.4.0",
    "eslint-config-prettier": "^6.3.0",
    "eslint-plugin-prettier": "^3.1.0",
    "prettier": "^1.18.2",
```

**Comment by lydell** [comment]
Hi!

`@typescript-eslint/indent` is already included:

https://github.com/prettier/eslint-config-prettier/blob/2a36c6dbac1ca70a5968e70e9fe9c6a3f8f86ced/%40typescript-eslint.js#L9

Maybe you forgot to add `"prettier/@typescript-eslint"` to the `"extends"` array in your ESLint configuration?

**Comment by rasenplanscher** [comment]
I see 🤔
Inherited the code base and did not check that 🤦‍♂️
Thank you for the pointer! I'm sorry for the waste of time...
