### ISSUE TITLE
Support TypeScript 3.7 `declare` class fields

### ISSUE THREAD

**Issue by ntucker** [prettier/eslint-config-prettier#122]
https://github.com/prettier/prettier/issues/6661

Input:

```typescript
class C extends B {
  declare p: 25
}
```

Output:

```typescript
class C extends B {
  p: 25;
}
```

Expected behavior:

same as the input

**Comment by ntucker** [comment]
Does this not work just because a new version of prettier hasn't been released since that patch landed?

**Comment by lydell** [comment]
Yes.
