### ISSUE TITLE
Add vue/dot-location and vue/keyword-spacing

### ISSUE THREAD

**Issue by xcatliu** [prettier/eslint-config-prettier#124]
[vue/dot-location](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/dot-location.md) and [vue/keyword-spacing](https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/keyword-spacing.md) are new rules in eslint-plugin-vue. They should be set as `'off'` in eslint-config-prettier

**Comment by lydell** [comment]
Thanks! Released in v6.6.0.
