### ISSUE TITLE
Confusion about curly

### ISSUE THREAD

**Issue by tschaub** [prettier/eslint-config-prettier#13]
With `eslint-config-prettier@1.5.0` we were successfully configuring ESLint with `"curly": ["error", "all"]`.  After f7a4b4ef47a461515df4962a6576b9629d8808dc, `eslint-config-prettier-check` now exits with an error code and this message:
```
The following rules can be enabled in some cases. See:
https://github.com/prettier/eslint-config-prettier#special-rules

- curly
```

The [readme](https://github.com/prettier/eslint-config-prettier/blob/v1.6.0/README.md#special-rules) still says this is a valid rule config:
```js
{
  "rules": {
    "curly": ["error", "all"]
  }
}
```

Should `eslint-config-prettier-check` really be failing with this config?

**Comment by lydell** [comment]
Are you saying that you want `eslint-config-prettier-check` to exit with a different status code if only "special rules" were found?

**Comment by tschaub** [comment]
I was surprised that `eslint-config-prettier-check` failed (with a non-zero exit code) when I have this config:
```js
{
  "rules": {
    "curly": ["error", "all"]
  }
}
```

In the 1.5.0 release, this config passes the check.  In 1.6.0, it fails.  And the readme says it is a valid rule config.

**Comment by lydell** [comment]
TODO:

- Exit with exit code zero if only special rules are found.
- Clarify the message for special rules to indicate that eslint-config-prettier-check only checks if special rules are enabled or not, but it is up to you to check if they are configured in a sensible way.

**Comment by lydell** [comment]
Does 1.7.0 let you achieve what you want without (or with less) confusion?

**Comment by tschaub** [comment]
Thanks for the update @lydell.  Regarding the exit code, any non-zero exit code is a failure, so this is still too strict to be used to decide if an eslint config is "valid" (where valid means that no conflicting rules are used).  I understand that the "special" rules may be conflicting, but it would be nice to be able to have the CLI tool *not* fail if only special rules are found.

This could be accomplished with args.  E.g.
```
eslint-config-prettier-check --ignore-curly
```

Or perhaps one `--ignore-special` arg.

I've been trying to use `eslint-config-prettier-check` as a script to test whether an ESLint config is valid (see the [`package.json` scripts here](https://github.com/planetlabs/eslint-config-planet/blob/bfb256c7507ca0ee83b0bdbb1073e57de8c56f64/package.json#L7-L9)).  The `test` script fails even if you use `curly` in a non-conflicting way.

I understand if you've got a different purpose for the project, but I think it would be nice to be able to use it to test ESLint configurations.  If it is going to be used as a test script, the CLI needs to exit with `0` for a valid config (and non-zero for invalid).  If parsing of the special rules configurations is out of scope, arguments to the CLI could be used to let the user determine what is valid.

In the meantime, `eslint-config-prettier@1.5.0` is working for my purposes.

**Comment by lydell** [comment]
@tschaub Check out 2.0.0. I think you’ll like it.
