### ISSUE TITLE
no-inline-comments and line-comment-position conflicts with ternary

### ISSUE THREAD

**Issue by EvgenyOrekhov** [prettier/eslint-config-prettier#132]
`no-inline-comments` and `line-comment-position` rules produce warnings after Prettier formats code with multiline ternary expressions.

## Steps to reproduce

In:

```js
const foo = barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
  // comment
  ? baz
  : qux;

```

Out:

```js
const foo = barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
  ? // comment
    baz
  : qux;

```

[Prettier playground demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCFMC8mARgIYBOlV1Ntd9DjTAOlJpgPQeaQC2vCGK3YB+EqQBewzEkwBHAK4APANysQAGhAQADjACW6ZKArkIAdwAKFBGmQhSANwj6AJppDFypMAGs4MADKOj76UADmyDDkCnBaABYwvAA2AOrx+vBoIWBwgbaZ+o6ZAJ72YGh2WmFocOQwlt7hvKTI2KTJtVoAVmhKAELefgGBpAIAMmFwbR1dIL1KgWHhyXAAigoQ8DOdcSAh5LXk9mTEJcnQHjrkYTCpbjDxyAAcAAxa1xC1qd469tdwI6OaZaRRbOCNXR2FCkNAAWigcDgrmRHnIcEU+nRjVIzVaSHauy0tV4+iiMT2aGWqw24J2cxgpGI91cj2QACYtNFSPpkssAMIQfj4kBQaAgkAKWoAFSZ0MJtQAvoqgA)

## Actual result

ESLint now gives warnings:

> Unexpected comment inline with code. (no-inline-comments)
> Expected comment to be above code. (line-comment-position)

[ESLint playground demo](https://eslint.org/demo#eyJ0ZXh0IjoiLyplc2xpbnRcbiAgbm8taW5saW5lLWNvbW1lbnRzOiBcImVycm9yXCIsXG4gIGxpbmUtY29tbWVudC1wb3NpdGlvbjogXCJlcnJvclwiXG4qL1xuXG5jb25zdCBmb28gPSBiYXJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJycnJyclxuICA/IC8vIGNvbW1lbnRcbiAgICBiYXpcbiAgOiBxdXg7XG4iLCJvcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYVZlcnNpb24iOjgsInNvdXJjZVR5cGUiOiJtb2R1bGUiLCJlY21hRmVhdHVyZXMiOnt9fSwicnVsZXMiOnt9LCJlbnYiOnt9fX0=)

## Expected result

No ESLint warnings.

**Comment by lydell** [comment]
Good points! Maybe we should add these as [special rules](https://github.com/prettier/eslint-config-prettier#special-rules) (“require special attention when writing code”).

Which eslint-config-* package are you using that include these rules?

**Comment by EvgenyOrekhov** [comment]
@lydell https://github.com/EvgenyOrekhov/eslint-config-hardcore

**Comment by EvgenyOrekhov** [comment]
@lydell I've never had problems with comments until I tried to put them inside a multiline ternary expression.

**Comment by EvgenyOrekhov** [comment]
There is an open issue in the Prettier repo regarding this behavior: https://github.com/prettier/prettier/issues/2076.

**Comment by lydell** [comment]
Looks like there’s a PR too: https://github.com/prettier/prettier/pull/6418

Would be nice if Prettier handled comments en ternaries better.

**Comment by ineo00048** [comment]
> 

view nw sector or sw switch see!!?.

**Comment by JounQin** [comment]
close in favor of https://github.com/prettier/prettier/issues/2076
