### ISSUE TITLE
Turn off @typescript-eslint/comma-spacing

### ISSUE THREAD

**Issue by ybiquitous** [prettier/eslint-config-prettier#134]
Hi, typescript-eslint has added `@typescript-eslint/comma-spacing` with the version [2.18.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v2.18.0)! 🎉 

eslint-config-prettier has already turned off the core rule [`comma-spacing`](https://eslint.org/docs/rules/comma-spacing), so I think it should turn off also `@typescript-eslint/comma-spacing`.

https://github.com/prettier/eslint-config-prettier/blob/4fdaa044ca252f2f6360dba9d6ef1e43bf03b59a/index.js#L30

See also:

- https://github.com/typescript-eslint/typescript-eslint/pull/1495
- https://github.com/typescript-eslint/typescript-eslint/blob/v2.18.0/packages/eslint-plugin/docs/rules/comma-spacing.md

**Comment by lydell** [comment]
Released in v6.10.0. Thanks for the great work as always!

**Comment by ybiquitous** [comment]
@lydell Thanks a lot for your instant response! 😄
