### ISSUE TITLE
Does no-floating-decimal still need to be turned off?

### ISSUE THREAD

**Issue by astorije** [prettier/eslint-config-prettier#138]
I see that `no-floating-decimal` was disabled in v2.6.0 (a while ago!):
https://github.com/prettier/eslint-config-prettier/commit/e47c6a6de6c3fae40f561759cb9fab79453db816

However, it seems to me that it doesn't affect Prettier in any way. Do you recall why you turned it off and marked it as conflicting in the checker CLI tool? Is it something we can re-enable nowadays, e.g. it was breaking the parser before?

**Comment by lydell** [comment]
It doesn’t conflict with Prettier – it’s _unnecessary_ when using Prettier, isn’t it?

**Comment by astorije** [comment]
Gotcha. Why is it unnecessary? It seems to me Prettier doesn't do anything about those, but I might be missing something.

**Comment by lydell** [comment]
Here’s the examples from https://eslint.org/docs/rules/no-floating-decimal:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwARQK4C22AvNgHQCsA3ADpQY75GkBMZt9WuhJ2AtGQDsVEABoQEAA4wAltADOyUFkwQA7gAUsCRSnSoIMgCZiQAI0zowAazgwAypKsyoAc2QxMeOOIAWMAgAbAHVfGXh5JzA4ex1wmVRwgE9kcHlFcRd5OEwYDUtXAnRkADN0QOzxACt5AA8AIUsbO3t0AjgAGRc4UvLKkBra+xdXQLgARTwIeF6KnxAnTGzMVLN0MzhA00lMFxhg4xhfZAAOAAZxHYhs4MtJVJ24ZdQe8QBHKfh8qV0QdHk+FA4HAjCDTJg4B8ZBD8uhCsUkGU5uJsgQZB4vPN5CMxpNpj1EX15jB1gcjEdkCxxJ50DJAiMAMIQAhFVJQaCvEB4bIAFXWuiR-VQ3gAklBQbB7GBdtIAILi+wwJJjWbZAC+aqAA)
```sh
--parser babel
```

**Input:**
```jsx
var num = .5;
var num = 2.;
var num = -.7;
```

**Output:**
```jsx
var num = 0.5;
var num = 2;
var num = -0.7;

```

**Comment by astorije** [comment]
Oh wow you are totally right and I am totally wrong ahah. I guess I was testing on a file that had a parsing error or something, and Prettier was not running. Apologies for the noise and thanks for the responses!
