### ISSUE TITLE
Drop Node 8 support

### ISSUE THREAD

**Issue by MichaelDeBoey** [prettier/eslint-config-prettier#140]
Because it's [EOL](https://nodejs.org/en/about/releases).

**Comment by lydell** [comment]
Yeah, we should drop it at some point. I don’t think we need an issue to track this, unless there was something specific this would help you with?

**Comment by MichaelDeBoey** [comment]
No specific reason except it's EOL.

If you need any help, I'm glad to help out and provide a PR. 🙂

**Comment by MichaelDeBoey** [comment]
It's probably a good idea to wait for ESLint 7, since that will drop Node 8.

https://github.com/eslint/eslint/releases/tag/v7.0.0-alpha.0
https://github.com/eslint/eslint/pull/12700

**Comment by lydell** [comment]
Ok, thanks for the info!

I think it makes sense to drop Node.js 8 at the same time as upgrading to ESLint 7 then.
