### ISSUE TITLE
How to make a for loop declaration stay on one line?

### ISSUE THREAD

**Issue by mdasfour** [prettier/eslint-config-prettier#144]
Hello,

In a typescript file that I am working on, prettier automatically moves what is in between the brackets of the for loop declaration on a separate line, like so:

for (
					let s = 0;
					s < a.length;
					s++
				)

I want it to be like this:

for ( let s = 0; s < a.length; s++ )

I have searched and tried different ways of getting it to format the way I want it, but to no avail.  Is there anyway I can go about getting prettier to format it the way I want?

Thanks.

**Comment by lydell** [comment]
Hi!

Generally speaking, you can’t influence what Prettier does. It decides on formatting so humans don’t need to think (or discuss!) about it.

This config does not change Prettier in any way. All it does is turning off a bunch of ESLint rules.

Note that even with 4-space indentation, it takes a fair amount of nesting before Prettier breaks your for loop like that:

**Prettier 2.0.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEw3o2gOlAZhAJwAIAKHAGzhiIGciBeIgBgG4c6AeIgQwDpKoAcxgALNlBoBqSTgCU4gL5LlKpSAA0ICAAcYAS2g1kobgQIQA7gAVTCIym7kL3AJ5HNAIwLcwAayoAyto+ekLIMAQArnCaIjAAtuQA6iJ68DTBYHABdml6AG5pLsjgNO4goTRwBDBW3oLx3Mi4jlWaAFY0AB4AQt5+gdzxcAAyoXDNrTEgnV0BoYKUAIqREPCT5G0gwQRVBCUe3B5w5BrbBKEwSXoAJqLIABxMmtrmVUne2iWvcHv5E5oAI6reB1HT2EDcGgAWigcDgNwRZwIcGBehRdW4DSaSBam2mVXienCUQJC2WIImuKmmhgR2udxEyAALLTvHpyAsAMIQeKNEq-ACsZ0iVQAKkd7HitvlogBJKCI2ABMAXXQAQUVARgLkoGyqSiAA)
```sh
--parser babel
--tab-width 4
```

**Input:**
```jsx
{{{{{{{{{{{{
for (
let s = 0;
s < a.length;
s++
);
}}}}}}}}}}}}
```

**Output:**
```jsx
{
    {
        {
            {
                {
                    {
                        {
                            {
                                {
                                    {
                                        {
                                            {
                                                for (
                                                    let s = 0;
                                                    s < a.length;
                                                    s++
                                                );
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```

So maybe the solution is to refactor your code a little bit?

**Comment by mdasfour** [comment]
Hi Simon,

Sorry for the late reply.  Thank you very much for your prompt response and help.  I appreciate it.

Thanks.
