### ISSUE TITLE
react/jsx-wrap-multilines not turned off for props

### ISSUE THREAD

**Issue by riwu** [prettier/eslint-config-prettier#148]
`"eslint-config-prettier": "^6.11.0"`
`"extends": ["airbnb", "prettier"]`
![image](https://user-images.githubusercontent.com/2226023/80918667-b5a11680-8d98-11ea-9400-a55689c742dc.png)

The rule `react/jsx-wrap-multilines` is not turned off which causes conflict with Prettier when a prop value is multiline JSX.

Bug seems to have occurred in the past: https://github.com/prettier/eslint-config-prettier/issues/3

**Comment by lydell** [comment]
Hi! You seem to have forgotten to add `"prettier/react"` to the `"extends"` array.

**Comment by riwu** [comment]
Thanks!
