### ISSUE TITLE
Add quote-props to special rules

### ISSUE THREAD

**Issue by EvgenyOrekhov** [prettier/eslint-config-prettier#150]
The `quote-props` rule has an additional [numbers](https://eslint.org/docs/rules/quote-props#numbers) option that can be enabled and still not conflict with Prettier, since Prettier preservers the original quotes for numbers ([playground demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEEBGArOMLAXk2AB0pNMBGAJgGYlNyQAzCCVgGkutYAsAVgBsrZqxwBDAE49KAXwDclENxAQADjACW6ZKFkyIAdwAKshGmQgpAGxNSAntfU4ZUsAGs4MAMqanjpQAObIMDIArnDqABYwALZ2AOqxOvBogWBwflbpOgBu6U42YGiuIMFocDIwZh4hCVLIbPbV6nhoAB4AQh7evn5SCXAAMsFwLW0xIJ1dfsEhdnAAipEQ8FN27SCBMtUyNtI4cHZquzLBMMk6ACYwscgAHAAM6prG1ckemjYfcAcCpN1ABHdbwepaawoKRoAC0UDgcFuyPOMjgYJ06PqUkazSQrW2M2qCR04SixMWyzWG0mBOm6hgUhwN3ujyQdEZHh0dkWAGEIAkmjYAUJzpFqgAVZnQwk7ArRACSUBRsD8YEu2gAgiq-DAnMsttUFAogA)).

So one can use the following configuration in addition to Prettier:

`"quote-props": ["error", "as-needed", { "numbers": true }]`

**Comment by lydell** [comment]
Hi!

Am I understanding this right – is `"quote-props": ["error", "as-needed", { "numbers": true }]` used to enforce quotes around numbers?

**Comment by EvgenyOrekhov** [comment]
@lydell Yes.

**Comment by lydell** [comment]
I opened a pull request to let Prettier quote/unquote numbers just like ESLint: https://github.com/prettier/prettier/pull/8508

When that’s merged, the only way to use ESLint’s `quote-props` together with Prettier is by setting `quoteProps: "preserve"` in Prettier, to let ESLint make the decisions completely on its own. But why would one want to do that? Any comments or thoughts?

**Comment by EvgenyOrekhov** [comment]
I would prefer Prettier to be more opinionated and use Prettier's defaults, and just disable ESLint's rule.

**Comment by EvgenyOrekhov** [comment]
Looks like this issue is no longer valid since Prettier 2.1 now quotes/unquotes number keys.
