### ISSUE TITLE
"Example configuration" in README includes redundant plugin fields

### ISSUE THREAD

**Issue by ZYinMD** [prettier/eslint-config-prettier#157]
In the [example configuration](https://github.com/prettier/eslint-config-prettier#example-configuration) part of the README, I think most of the plugins are unnecessary. For instance, the `"plugin:react/recommended"` config file already contains `plugin: ["react"]`, and the the `"plugin:@typescript-eslint/recommended"` config file already contains `plugin: [ "@typescript-eslint"]`. Generally speaking, if you extend a config file that is exported by a plugin, then you won't need to manually add that plugin in your `plugin: []`.

It'd also be nice if the README could explain about this fact a little bit. Lots of developers actually don't understand eslint config to this extent, they usually just copy paste.

I'm not an eslint expert either, so please correct me if I'm wrong.

**Comment by lydell** [comment]
You’re right, we should remove the unnecessary parts. Bad examples are bad.

**Comment by lydell** [comment]
I removed the entire "Example configuration" section since it provides nothing in addition to the previous sections and is a bad example.
