### ISSUE TITLE
Turn off @typescript-eslint/comma-dangle

### ISSUE THREAD

**Issue by miZyind** [prettier/eslint-config-prettier#158]
There is a new extension rule in `typescript-eslint` since the version [4.2.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v4.2.0) has been released.

The core config has already turned off [comma-dangle](https://eslint.org/docs/rules/comma-dangle).
The config of `typescript-eslint` should respect the same rule as well.

https://github.com/prettier/eslint-config-prettier/blob/9444ee0b20f9af3ff364f62d6a9ab967ad673a9d/index.js#L29

Reference:
- [typescript-eslint/typescript-eslint#2416](https://github.com/typescript-eslint/typescript-eslint/pull/2416)
- [typescript-eslint/docs/rules/comma-dangle.md](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/comma-dangle.md)

**Comment by lydell** [comment]
Released in v6.12.0. Thank for the report, and thanks @ybiquitous for the pull request!
