### ISSUE TITLE
How can I set Prettier Arguments?

### ISSUE THREAD

**Issue by respectTheCode** [prettier/eslint-config-prettier#16]
Specifically I am looking to turn on the `useTabs` argument.

**Comment by lydell** [comment]
`prettier --use-tabs`?

**Comment by respectTheCode** [comment]
Found it

```
	rules: {
		"prettier/prettier": ["error", {
			useTabs: true
		}]
	}
```

I am pretty sure this was in the readme a few days ago.

**Comment by respectTheCode** [comment]
Wait that is for a different module `eslint-plugin-prettier`
