### ISSUE TITLE
Support for eslint-config-vue v7 (which support Vue.js 3.0)

### ISSUE THREAD

**Issue by xcatliu** [prettier/eslint-config-prettier#161]
[eslint-config-vue@7.0.0](https://github.com/vuejs/eslint-plugin-vue/releases/tag/v7.0.0) added 66 new rules and lot's of them should be disabled in eslint-config-prettier. Here are the new rules (rule needs to be disabled are checked (draft)):

- [x] [vue/comma-spacing](https://eslint.vuejs.org/rules/comma-spacing.html)
- [x] [vue/comma-style](https://eslint.vuejs.org/rules/comma-style.html)
- [ ] [vue/custom-event-name-casing](https://eslint.vuejs.org/rules/custom-event-name-casing.html)
- [ ] [vue/dot-notation](https://eslint.vuejs.org/rules/dot-notation.html)
- [ ] [vue/experimental-script-setup-vars](https://eslint.vuejs.org/rules/experimental-script-setup-vars.html)
- [x] [vue/func-call-spacing](https://eslint.vuejs.org/rules/func-call-spacing.html)
- [ ] [vue/html-comment-content-newline](https://eslint.vuejs.org/rules/html-comment-content-newline.html)
- [ ] [vue/html-comment-content-spacing](https://eslint.vuejs.org/rules/html-comment-content-spacing.html)
- [ ] [vue/html-comment-indent](https://eslint.vuejs.org/rules/html-comment-indent.html)
- [ ] [vue/no-arrow-functions-in-watch](https://eslint.vuejs.org/rules/no-arrow-functions-in-watch.html)
- [ ] [vue/no-bare-strings-in-template](https://eslint.vuejs.org/rules/no-bare-strings-in-template.html)
- [ ] [vue/no-custom-modifiers-on-v-model](https://eslint.vuejs.org/rules/no-custom-modifiers-on-v-model.html)
- [ ] [vue/no-deprecated-data-object-declaration](https://eslint.vuejs.org/rules/no-deprecated-data-object-declaration.html)
- [ ] [vue/no-deprecated-destroyed-lifecycle](https://eslint.vuejs.org/rules/no-deprecated-destroyed-lifecycle.html)
- [ ] [vue/no-deprecated-dollar-listeners-api](https://eslint.vuejs.org/rules/no-deprecated-dollar-listeners-api.html)
- [ ] [vue/no-deprecated-dollar-scopedslots-api](https://eslint.vuejs.org/rules/no-deprecated-dollar-scopedslots-api.html)
- [ ] [vue/no-deprecated-events-api](https://eslint.vuejs.org/rules/no-deprecated-events-api.html)
- [ ] [vue/no-deprecated-filter](https://eslint.vuejs.org/rules/no-deprecated-filter.html)
- [ ] [vue/no-deprecated-functional-template](https://eslint.vuejs.org/rules/no-deprecated-functional-template.html)
- [ ] [vue/no-deprecated-html-element-is](https://eslint.vuejs.org/rules/no-deprecated-html-element-is.html)
- [ ] [vue/no-deprecated-inline-template](https://eslint.vuejs.org/rules/no-deprecated-inline-template.html)
- [ ] [vue/no-deprecated-props-default-this](https://eslint.vuejs.org/rules/no-deprecated-props-default-this.html)
- [ ] [vue/no-deprecated-v-bind-sync](https://eslint.vuejs.org/rules/no-deprecated-v-bind-sync.html)
- [ ] [vue/no-deprecated-v-on-native-modifier](https://eslint.vuejs.org/rules/no-deprecated-v-on-native-modifier.html)
- [ ] [vue/no-deprecated-v-on-number-modifiers](https://eslint.vuejs.org/rules/no-deprecated-v-on-number-modifiers.html)
- [ ] [vue/no-deprecated-vue-config-keycodes](https://eslint.vuejs.org/rules/no-deprecated-vue-config-keycodes.html)
- [ ] [vue/no-dupe-v-else-if](https://eslint.vuejs.org/rules/no-dupe-v-else-if.html)
- [ ] [vue/no-duplicate-attr-inheritance](https://eslint.vuejs.org/rules/no-duplicate-attr-inheritance.html)
- [ ] [vue/no-empty-component-block](https://eslint.vuejs.org/rules/no-empty-component-block.html)
- [x] [vue/no-extra-parens](https://eslint.vuejs.org/rules/no-extra-parens.html)
- [ ] [vue/no-lifecycle-after-await](https://eslint.vuejs.org/rules/no-lifecycle-after-await.html)
- [ ] [vue/no-lone-template](https://eslint.vuejs.org/rules/no-lone-template.html)
- [ ] [vue/no-multiple-objects-in-class](https://eslint.vuejs.org/rules/no-multiple-objects-in-class.html)
- [ ] [vue/no-multiple-slot-args](https://eslint.vuejs.org/rules/no-multiple-slot-args.html)
- [ ] [vue/no-multiple-template-root](https://eslint.vuejs.org/rules/no-multiple-template-root.html)
- [ ] [vue/no-mutating-props](https://eslint.vuejs.org/rules/no-mutating-props.html)
- [ ] [vue/no-potential-component-option-typo](https://eslint.vuejs.org/rules/no-potential-component-option-typo.html)
- [ ] [vue/no-ref-as-operand](https://eslint.vuejs.org/rules/no-ref-as-operand.html)
- [ ] [vue/no-restricted-component-options](https://eslint.vuejs.org/rules/no-restricted-component-options.html)
- [ ] [vue/no-restricted-static-attribute](https://eslint.vuejs.org/rules/no-restricted-static-attribute.html)
- [ ] [vue/no-restricted-v-bind](https://eslint.vuejs.org/rules/no-restricted-v-bind.html)
- [ ] [vue/no-setup-props-destructure](https://eslint.vuejs.org/rules/no-setup-props-destructure.html)
- [ ] [vue/no-sparse-arrays](https://eslint.vuejs.org/rules/no-sparse-arrays.html)
- [ ] [vue/no-template-target-blank](https://eslint.vuejs.org/rules/no-template-target-blank.html)
- [ ] [vue/no-unregistered-components](https://eslint.vuejs.org/rules/no-unregistered-components.html)
- [ ] [vue/no-unused-properties](https://eslint.vuejs.org/rules/no-unused-properties.html)
- [ ] [vue/no-useless-concat](https://eslint.vuejs.org/rules/no-useless-concat.html)
- [ ] [vue/no-useless-mustaches](https://eslint.vuejs.org/rules/no-useless-mustaches.html)
- [ ] [vue/no-useless-v-bind](https://eslint.vuejs.org/rules/no-useless-v-bind.html)
- [ ] [vue/no-v-for-template-key-on-child](https://eslint.vuejs.org/rules/no-v-for-template-key-on-child.html)
- [ ] [vue/no-v-for-template-key](https://eslint.vuejs.org/rules/no-v-for-template-key.html)
- [ ] [vue/no-v-model-argument](https://eslint.vuejs.org/rules/no-v-model-argument.html)
- [ ] [vue/no-watch-after-await](https://eslint.vuejs.org/rules/no-watch-after-await.html)
- [x] [vue/object-curly-newline](https://eslint.vuejs.org/rules/object-curly-newline.html)
- [x] [vue/object-property-newline](https://eslint.vuejs.org/rules/object-property-newline.html)
- [ ] [vue/one-component-per-file](https://eslint.vuejs.org/rules/one-component-per-file.html)
- [x] [vue/operator-linebreak](https://eslint.vuejs.org/rules/operator-linebreak.html)
- [ ] [vue/prefer-template](https://eslint.vuejs.org/rules/prefer-template.html)
- [ ] [vue/require-explicit-emits](https://eslint.vuejs.org/rules/require-explicit-emits.html)
- [ ] [vue/require-slots-as-functions](https://eslint.vuejs.org/rules/require-slots-as-functions.html)
- [ ] [vue/require-toggle-inside-transition](https://eslint.vuejs.org/rules/require-toggle-inside-transition.html)
- [ ] [vue/return-in-emits-validator](https://eslint.vuejs.org/rules/return-in-emits-validator.html)
- [x] [vue/space-in-parens](https://eslint.vuejs.org/rules/space-in-parens.html)
- [x] [vue/template-curly-spacing](https://eslint.vuejs.org/rules/template-curly-spacing.html)
- [ ] [vue/v-for-delimiter-style](https://eslint.vuejs.org/rules/v-for-delimiter-style.html)
- [ ] [vue/valid-v-is](https://eslint.vuejs.org/rules/valid-v-is.html)

**Comment by lydell** [comment]
Awesome! Do you want to make a pull request for this eventually?

**Comment by xcatliu** [comment]
Sure! Let me do this

**Comment by lydell** [comment]
Thanks! Released in v6.13.0.
