### ISSUE TITLE
Looks like we need to do something about no-confusing-arrow again…

### ISSUE THREAD

**Issue by lydell** [prettier/eslint-config-prettier#17]
prettier/prettier#1450 wants to change this:

```js
var x = a =>
  (1 ? 2 : 3);
```

into:

```js
var x = a =>
  1 ? 2 : 3;
```

which would violate no-confusing-arrow.

Potentially suggest this to ESLint as well – that’s not really a confusing case, is it?

**Comment by vjeux** [comment]
I don't recommend people to use no-confusing-arrow alongside prettier. I followed the suggestion as it's a legitimate thing to add parenthesis when in one line. But when broken in multiple lines there is not confusion so it doesn't make sense (and it makes the output look bad).

Would be nice to get eslint proper to update their rule indeed.

**Comment by ljharb** [comment]
"look bad" is subjective; to be, the "into" above looks bad, but this would look good:
```js
var x = a => (
  1 ? 2 : 3
);
```

Is there any chance you'd be willing to make this a config option?

**Comment by lydell** [comment]
@ljharb Did you mean to open an issue on Prettier? This repo is just an ESLint config that turns a bunch of rules off.

**Comment by ljharb** [comment]
@lydell ah, thanks :-) i will open an issue on prettier; i was responding to the discussion in this thread tho.

**Comment by Garrett-R** [comment]
I've filed an issue on ESLint here: https://github.com/eslint/eslint/issues/16662
