### ISSUE TITLE
In v8.0.0 prettier/recommend is it imported too?

### ISSUE THREAD

**Issue by SandHilt** [prettier/eslint-config-prettier#176]
In changelog has written:

> The "prettier" config now includes not just ESLint core rules, but also rules from all plugins. Much simpler!

Reference: [CHANGELOG.md](https://github.com/prettier/eslint-config-prettier/blob/main/CHANGELOG.md#version-800-2021-02-21)

This also included `plugin:prettier/recommended` ?

Sorry for the silly question, is that like the others are part of `prettier/*`.

**Comment by lydell** [comment]
Hi!

The answer is: No.

Everything in `"extends"` that start with `plugin:` comes from _plugins._ This is a config, so it’s not coming from this package (it comes from eslint-<strong>plugin</strong>-prettier itself). If think it’s sad that the whole eslint-config-prettier + eslint-plugin-prettier thing is so confusing. See also: https://github.com/prettier/eslint-config-prettier#arrow-body-style-and-prefer-arrow-callback

A tip for the future – it’s easy to look at the source code for ESLint configs to see exactly what they do.

**Comment by lydell** [comment]
One thing I forgot to mention: It’s almost the other way around. `"plugin:prettier/recommended"` includes the `"prettier"` config from this repo. So if you use `eslint-plugin-prettier`, `"plugin:prettier/recommended"` should be all you need.

**Comment by lydell** [comment]
See also #177
