### ISSUE TITLE
Disable react/no-unescaped-entities

### ISSUE THREAD

**Issue by smably** [prettier/eslint-config-prettier#18]
Prettier converts `&apos;` to `'` in JSX text ([test case](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20default%20function%20Component()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3Cdiv%3E%5Cn%20%20%20%20%20%20It%26apos%3Bs%20some%20content%5Cn%20%20%20%20%3C%2Fdiv%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)), but [`react/no-unescaped-entities`](
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unescaped-entities.md) complains that it should be an HTML entity.

**Comment by lydell** [comment]
Let's wait for the next Prettier release (tomorrow?). I know it contains updates on how JSX is escaped.

**Comment by smably** [comment]
Looks like the output is the same in 1.3.0.

**Comment by lydell** [comment]
My bad, it appears that the PR for JSX escaping stuff wasn't merged until just now (so it didn't make it into the 1.3.0 release): prettier/prettier#1165. I just tested it, and that leaves `&apos;` and friends alone. So I think we should just leave this issue open until the next version of Prettier is released.

**Comment by smably** [comment]
Ah, good catch. Let's wait and see then. Thanks for following up!

**Comment by lydell** [comment]
There's now been a Prettier release with the JSX escaping stuff in it.
