### ISSUE TITLE
Prettier configured with tabs conflicts with no-mixed-spaces-and-tabs

### ISSUE THREAD

**Issue by jf908** [prettier/eslint-config-prettier#185]
When Prettier is configured with tabs, it mixes spaces and tabs for alignment.
There is an ESLint rule that allows this:

`'no-mixed-spaces-and-tabs': ['error', 'smart-tabs']`

but it doesn't seem to be configured by eslint-config-prettier.

**Comment by lydell** [comment]
Hi! eslint-config-prettier turns off that rule here: https://github.com/prettier/eslint-config-prettier/blob/56213e4f454fbe6c187d15b52a2c91df8b414b3c/index.js#L56

You can use the CLI helper tool to find problems with your configuration: https://github.com/prettier/eslint-config-prettier#cli-helper-tool

**Comment by jf908** [comment]
Thanks!

Just a silly problem on my end where the project had `eslint:recommended` after `plugin:prettier/recommended` in the extends list.
