### ISSUE TITLE
change rules name from `babel/*` to `@babel/*`

### ISSUE THREAD

**Issue by ChipZhang** [prettier/eslint-config-prettier#186]
this package only covers rules `babel/*`, provided by the discontinued package `eslint-plugin-babel`

the rule names of the new package `@babel/eslint-plugin` is `@babel/*`

https://github.com/babel/eslint-plugin-babel#note-eslint-plugin-babel-is-now-babeleslint-plugin-and-has-moved-into-the-babel-monorepo

**Comment by lydell** [comment]
Thanks for the heads up!

I think we should support both for a while to make it easier for folks to upgrade.

**Comment by lydell** [comment]
Released in v8.3.0.
