### ISSUE TITLE
Broken with typescript@4.3 override feature

### ISSUE THREAD

**Issue by Saul-Mirone** [prettier/eslint-config-prettier#194]
```typescript
export class Blockquote extends Node {
    id = 'blockquote';
 
   // ->  error  Parsing error: ';' expected  prettier/prettier
    override inputRules = () => [];
}
```

**Comment by lydell** [comment]
Hi!

You have reported this issue in eslint-<strong>config</strong>-prettier. All the config does is turning off a bunch of ESLint rules, so your problem can’t possibly come from this repo.

The error message says `prettier/prettier` – that’s the ESLint rule name that reported the error. That rule comes from [eslint-<strong>plugin</strong>-plugin](https://github.com/prettier/eslint-plugin-prettier). But that rule is just a small wrapper around the actual [Prettier](https://github.com/prettier/prettier/) package – that’s the root of the problem.

If you go to [Prettier’s issue tracker](https://github.com/prettier/prettier/issues/) you’ll see a pinned issue right at the top – [TypeScript 4.3](https://github.com/prettier/prettier/issues/10642).

That issue says that currently you need to use the `babel-ts` parser to use `override`: https://github.com/prettier/prettier/issues/10642#issuecomment-849879761

Your example seems to work in the Prettier playground when switching to the `babel-ts` parser:

**Prettier 2.3.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAIUIjAGsBHAVwnj3XigBMKA5CLnDzAAOlDwS8ASy54AvHgDkAIxr1mrOIoDcYvHokB6Q3gC0APglxs2HBIAKxbKSlQA5uxs4kS7YvaYcGDwsngY2HAwMFLWhuGR0dYGEhAAbtbYMkKuGEwwAEpMhHAUCgAUAJTylgDaALq6UAC+IAA0IBAY0dCkyKBOtgDujhFQvSjEhIPEAJ697crYxPSRAMoYy65uyDDYTHDtcAC2ynBcglwAMsTuTMRucABiOEfEUVvIIMR5EG0gABYwI6EADq-yk8FIGzAcFWCBc0VSEJmnzA5D+rlI1hg9iWbleyAAZpMse0AFakNCUJYrGCrYhHOCXVxwIkkg4gCloVZbYoARRY8DZhFJIA2zmsn2UxFOhFMMHmYsysBBMhg-2QAA4AAztcIQLEgpYYT7xLHYdJ-DTwXGdcZfUimKBwM5nP4RZhSCK4+4EpDEkUcrFHKQ7PZB3lwAWaYWimAy1VcdXIABM7V2xCkhC2AGEIEc-ahSABWP5MLEAFRl4wDotS+wAktwEHSwJkugBBbirGAzYqxuBNJpAA)

```sh
--parser babel-ts
```

**Input:**

```tsx
export class Blockquote extends Node {
    id = 'blockquote';
 
   // ->  error  Parsing error: ';' expected  prettier/prettier
    override inputRules = () => [];
}
```

**Output:**

```tsx
export class Blockquote extends Node {
  id = "blockquote";

  // ->  error  Parsing error: ';' expected  prettier/prettier
  override inputRules = () => [];
}

```

Please try to investigate a little bit more yourself next time, it’s not super hard! 🙏

**Comment by Saul-Mirone** [comment]
> Hi!
> 
> You have reported this issue in eslint-**config**-prettier. All the config does is turning off a bunch of ESLint rules, so your problem can’t possibly come from this repo.
> 
> The error message says `prettier/prettier` – that’s the ESLint rule name that reported the error. That rule comes from [eslint-**plugin**-plugin](https://github.com/prettier/eslint-plugin-prettier). But that rule is just a small wrapper around the actual [Prettier](https://github.com/prettier/prettier/) package – that’s the root of the problem.
> 
> If you go to [Prettier’s issue tracker](https://github.com/prettier/prettier/issues/) you’ll see a pinned issue right at the top – [TypeScript 4.3](https://github.com/prettier/prettier/issues/10642).
> 
> That issue says that currently you need to use the `babel-ts` parser to use `override`: [prettier/prettier#10642 (comment)](https://github.com/prettier/prettier/issues/10642#issuecomment-849879761)
> 
> Your example seems to work in the Prettier playground when switching to the `babel-ts` parser:
> 
> **Prettier 2.3.0**
> [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAIUIjAGsBHAVwnj3XigBMKA5CLnDzAAOlDwS8ASy54AvHgDkAIxr1mrOIoDcYvHokB6Q3gC0APglxs2HBIAKxbKSlQA5uxs4kS7YvaYcGDwsngY2HAwMFLWhuGR0dYGEhAAbtbYMkKuGEwwAEpMhHAUCgAUAJTylgDaALq6UAC+IAA0IBAY0dCkyKBOtgDujhFQvSjEhIPEAJ697crYxPSRAMoYy65uyDDYTHDtcAC2ynBcglwAMsTuTMRucABiOEfEUVvIIMR5EG0gABYwI6EADq-yk8FIGzAcFWCBc0VSEJmnzA5D+rlI1hg9iWbleyAAZpMse0AFakNCUJYrGCrYhHOCXVxwIkkg4gCloVZbYoARRY8DZhFJIA2zmsn2UxFOhFMMHmYsysBBMhg-2QAA4AAztcIQLEgpYYT7xLHYdJ-DTwXGdcZfUimKBwM5nP4RZhSCK4+4EpDEkUcrFHKQ7PZB3lwAWaYWimAy1VcdXIABM7V2xCkhC2AGEIEc-ahSABWP5MLEAFRl4wDotS+wAktwEHSwJkugBBbirGAzYqxuBNJpAA)
> 
> ```shell
> --parser babel-ts
> ```
> 
> **Input:**
> 
> ```tsx
> export class Blockquote extends Node {
>     id = 'blockquote';
>  
>    // ->  error  Parsing error: ';' expected  prettier/prettier
>     override inputRules = () => [];
> }
> ```
> 
> **Output:**
> 
> ```tsx
> export class Blockquote extends Node {
>   id = "blockquote";
> 
>   // ->  error  Parsing error: ';' expected  prettier/prettier
>   override inputRules = () => [];
> }
> ```
> 
> Please try to investigate a little bit more yourself next time, it’s not super hard! 🙏

Thanks for your reply! I'll close this.

**Comment by JeanMeche** [comment]
If anyone is reading this, upgrade `prettier` to 2.3.1+ will fix this.

**Comment by omril1** [comment]
@JeanMeche That didn't work for me
