### ISSUE TITLE
@typescript-eslint/quotes not blocked

### ISSUE THREAD

**Issue by jtheberge** [prettier/eslint-config-prettier#204]
Hi, it looks like eslint's quote rule is blocked, but not @typescript-eslint/quotes.

**Comment by lydell** [comment]
https://github.com/prettier/eslint-config-prettier/blob/866a562bcd86bca75da3b268d2cc0eb1143fd81b/index.js#L18

**Comment by jtheberge** [comment]
So weird, I extended the config and this rule was not being disabled despite being last in the array. I think my IDE wasn't reading it correctly, because today now I no longer need to manually disable this rule 🤦
