### ISSUE TITLE
Report about `react` rules in `eslint-config-prettier-check`

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/eslint-config-prettier#21]

**Comment by lydell** [comment]
Well, there’s a [test for that](https://github.com/prettier/eslint-config-prettier/blob/e137ae7d6691bb0d7995275c0f1ecfef2f10cca0/test/cli.js#L151).

Perhaps you’ve run into a bug? Could you share what you tried, what your expectation was and what really happened?

**Comment by evilebottnawi** [comment]
@lydell my bug, sorry
