### ISSUE TITLE
Problem with setting "curly"

### ISSUE THREAD

**Issue by gabmontes** [prettier/eslint-config-prettier#219]
This config turns off `curly` by default but that seems inconsistent with Prettier's stance about braces:

> Here are a few examples of things that are out of scope for Prettier:
> - Adding/removing {} and return where they are optional.

https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about

In addition, given that this config should be put last in the "extends" list, it prevents any other previous configs to set the rule and forces to explicitly configuring the rule in the "rules" section.

IMO the following line has to be removed.

https://github.com/prettier/eslint-config-prettier/blob/3dfe8c6301897260486e13bc22712e824958c422/index.js#L10

Would really appreciate your thoughts on this.

**Comment by lydell** [comment]
Hi! Have you read the documentation? https://github.com/prettier/eslint-config-prettier#curly

**Comment by lydell** [comment]
Closing because no response.
