### ISSUE TITLE
Prettier 1.4.x breaks linting

### ISSUE THREAD

**Issue by ZeeCoder** [prettier/eslint-config-prettier#22]
I'm not really sure how the plugin works, but if I upgrade to the new prettier, linting fails.
I'm not sure what I need to do to make it work. :/

Basically, it complains that some newlines should not be there anymore:
`error  Delete `⏎···`  prettier/prettier`

Even if I run the new version of prettier on my code however, nothing changes, and linting still fails.

This is the report I got from greenkeeper: https://github.com/ZeeCoder/container-query/issues/39#issuecomment-305984494

Cheers

**Comment by lydell** [comment]
This is not a plugin, it is a config. The message you posted seem to come from [eslint-<strong>plugin</strong>-prettier](https://github.com/prettier/eslint-plugin-prettier).

**Comment by ZeeCoder** [comment]
Ah sorry!
