### ISSUE TITLE
Configuring to avoid only unresolvable conflicts

### ISSUE THREAD

**Issue by luxaritas** [prettier/eslint-config-prettier#227]
Currently I am using eslint-config-prettier, but after discovering prettier-eslint I'm imagining it would be nice to let style defaults from eg Airbnb override prettier. However, my concern is that if I remove eslint-config-prettier then go the route of prettier then eslint --fix, that there may be some things that eslint won't fix but will error on, which if I try to change prettier would just revert, leaving me stuck.

First off, is this even a realistic concern to begin with? If so, could eslint-config-prettier expose a config which _only_ disables rules which could create this situation? Or could I get the same effect by requiring this config directly and just keeping the rules disabled that can't be auto fixed (ie, removing the changes to rules that can be auto fixed so that my configuration can take precedence)?

Let me know if I'm completely off base here. Thanks in advance for any guidance.

**Comment by JounQin** [comment]
Maybe you want https://github.com/prettier/eslint-plugin-prettier with:

```json
{
  "extends": ["plugin:prettier/recommended"]
}
```

**Comment by luxaritas** [comment]
That just winds up enabling this config, yeah? Which doesn't really address my question...

**Comment by JounQin** [comment]
`prettier` is just opinionated, maybe you want https://github.com/prettier/prettier-eslint

Please don't post **question** as issue next time.

https://github.com/prettier/prettier/discussions is for questions.

**Comment by luxaritas** [comment]
Oh, sorry! Missed discussions since I've been on mobile... I'll move there for further followup
