### ISSUE TITLE
How to tell eslint where my config file is?

### ISSUE THREAD

**Issue by suchy** [prettier/eslint-config-prettier#237]
I like to keep my config files in the config folder. Unfortunately looks like now eslint has no idea about the prettier config and ignores it. How can I set a prettier config path?

**Comment by lydell** [comment]
Hi!

All eslint-config-prettier does is turn off a bunch of ESLint rules. It has nothing to do with Prettier, other than the turned off ESLint rules being related to code formatting that overlaps with Prettier.

So there is no such thing as setting a Prettier config path in the context of eslint-config-prettier.

Maybe you opened the issue in the wrong place?

**Comment by suchy** [comment]
Hey,thanks for quick answer. Yeap, I should be checking eslint-plugin-prettier. 

I found solution here: https://github.com/prettier/eslint-plugin-prettier/issues/246. Leaveing it here in case someone else will read that in future.

Thanks.
