### ISSUE TITLE
Global installation

### ISSUE THREAD

**Issue by Lippiece** [prettier/eslint-config-prettier#239]
Is there any way to make it work with eslint installed globally? When I install this config with -g, eslint throws an error that it can't find "prettier" to extend from.

.eslintrc.yaml:
```
extends:
...
  - "prettier"
```

```
$ npm ls -g
/usr/lib
├── eslint-config-prettier@8.6.0
...
├── eslint@8.27.0
...
└── npm@8.19.2
```

**Comment by Lippiece** [comment]
Managed to workaround by setting:
```
extends:
...
  - "<path-to-global-modules-dir>/node_modules/eslint-config-prettier"

**Comment by lydell** [comment]
Hi! There is nothing special with eslint-config-prettier. (In fact, it’s one of the simplest configs in existence.) If you try this with some other config you should get the same result. You need to search for this yourself, or ask in some ESLint forum.
