### ISSUE TITLE
Prettier overrides Eslint

### ISSUE THREAD

**Issue by prince-of-maroc** [prettier/eslint-config-prettier#241]
This package doesn't seem to be working for me. I have configured ESLint with the Airbnb style guide, but Prettier is not adapting to this. For example, Prettier is throwing errors for single quotes, even though the Airbnb style guide requires single quotes.

Is there something else I should be doing if I am using a style guide for ESLint?

**Comment by lydell** [comment]
Hi! That’s how this package works – it disables parts of ESLint and lets Prettier decide. It does not configure Prettier in any way.

If you would like it to be the other way around (which I don’t recommend, but anyway), you can try [prettier-eslint](https://github.com/prettier/prettier-eslint).

**Comment by prince-of-maroc** [comment]
I thought it disabled parts of Prettier to conform with ESLint... noob moment. Thank you.
