### ISSUE TITLE
@typescript-eslint/block-spacing and @typescript-eslint/key-spacing are not turned off

### ISSUE THREAD

**Issue by 8NAF** [prettier/eslint-config-prettier#242]
Hi,
I noticed in the [index.js](https://github.com/prettier/eslint-config-prettier/blob/main/index.js) file that you have turned off two rules: `block-spacing` and `vue/block-spacing`, but you didn't turn off [`@typescript-eslint/block-spacing`](https://typescript-eslint.io/rules/block-spacing/). Similarly, `key-spacing` and `vue/key-spacing` have been turned off, but [`@typescript-eslint/key-spacing`](https://typescript-eslint.io/rules/key-spacing/) has not. Is there a reason for this ?

**Comment by lydell** [comment]
Hi!

Those two `@typescript-eslint` rules are quite new and nobody has added here yet. Would you like to make a PR?

**Comment by ttionya** [comment]
Hi, I created a PR #243 for this issue.

**Comment by lydell** [comment]
Released in v8.7.0.

**Comment by 8NAF** [comment]
@ttionya
Thank you for creating the pull request. I forgot that I had also created this issue 😅.
