### ISSUE TITLE
airbnb rule "no-unexpected-multiline" not covered

### ISSUE THREAD

**Issue by cangoektas** [prettier/eslint-config-prettier#25]
Hi there,

I ran into a small problem. For the following eslint config:

```json
{
  "extends": ["airbnb-base", "prettier"]
}
```

and this non-pretty code:

```js
const objectWithFunctions = {
  foo: (value) => Promise.resolve(value)
};

const functionThatReturnsObject = () => objectWithFunctions;

const someVariableThatGivesUsTheKey = 'foo';

functionThatReturnsObject()[someVariableThatGivesUsTheKey]('hello world').then(res => console.log(res))
```

Prettier outputs the following:

```js
const objectWithFunctions = {
  foo: value => Promise.resolve(value),
};

const functionThatReturnsObject = () => objectWithFunctions;

const someVariableThatGivesUsTheKey = 'foo';

functionThatReturnsObject()
  [someVariableThatGivesUsTheKey]('hello world')
  .then(res => console.log(res));
```

and ESLint complains with the following:

```
error  Unexpected newline between object and [ of property access  no-unexpected-multiline
```

Not sure if this is an issue with the config here or maybe even with Prettier itself. If it's something with the config I could help out with a PR.

Using:
- prettier@1.5.3
- eslint-config-airbnb@15.0.1
- eslint-config-prettier@2.3.0
- eslint@3.19.0

**Comment by lydell** [comment]
Thanks for your issue! I don't have time to look at this right now. Could you read through #8 in the meantime and see if anything in there helps?

**Comment by cangoektas** [comment]
Hey... sorry, completely forgot about this issue. I checked it and no, the rule `no-unexpected-multiline` was not mentioned in there.

**Comment by lydell** [comment]
I'm confused ... as far as I can tell the `no-unexpected-multiline` is mentioned 3 or 4 times in #8?

**Comment by cangoektas** [comment]
@lydell So sorry, you are absolutely right. Don't know what I was reading... I'll close this issue
