### ISSUE TITLE
Prettier 3: 

### ISSUE THREAD

**Issue by sj-dg** [prettier/eslint-config-prettier#254]
Prettier 3.0 has removed `prettier.resolveConfig.sync` - [more info here](https://prettier.io/blog/2023/07/05/3.0.0.html#change-public-apis-to-asynchronous-12574httpsgithubcomprettierprettierpull12574-12788httpsgithubcomprettierprettierpull12788-12790httpsgithubcomprettierprettierpull12790-13265httpsgithubcomprettierprettierpull13265-by-fiskerhttpsgithubcomfisker)

This package is throwing `prettier.resolveConfig.sync is not a function` at `/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:138:40)`

I am using `4.0.0` version of this package.

**Comment by lydell** [comment]
Hi! You seem to have posted this issue in the wrong repo. Follow along here instead: https://github.com/prettier/eslint-plugin-prettier/issues/562
