### ISSUE TITLE
How to add brace-style rules to prettier?

### ISSUE THREAD

**Issue by psyanite** [prettier/eslint-config-prettier#26]
So I want to use stroustrup for my brace-style, I updated my .eslintrc file as per below but prettier keeps complaining and I can only suppress the prettier/prettier rule in WebStorm.

```
  rules: {

    ...

    'brace-style': [
      'error',
      'stroustrup',
      {
        'allowSingleLine': true
      }
    ],

    'prettier/prettier': [
      'error',
      {
        singleQuote: true,
        trailingComma: 'all',
      },
    ],
  },
```

It keeps complaining about this:
```
  if (isMeow()) {
    meow();
  }
  else {
    bork();
  }
```

Thanks for reading my question 👍

**Comment by lydell** [comment]
There are two ways of using Prettier and ESLint at the same time:

1. Let Prettier handle the formatting of your code, and turn off all stylistic rules in ESLint (because they mostly conflict with Prettier, like in your case). eslint-config-prettier helps doing this.

2. Use [prettier-eslint](https://github.com/prettier/prettier-eslint). This runs Prettier first, and _then_ `eslint --fix`. This is if you disagree with some code formatting choice that Prettier has made, and want ESLint to automatically adjust that.

It looks like you are currently using method 1, but actually want method 2. So try out [prettier-eslint](https://github.com/prettier/prettier-eslint)!

**Comment by psyanite** [comment]
@lydell Thanks for taking the time and effort to respond to my question. I really appreciate it. Things are much more clear from your explanation now thank you so much.

**Comment by cybermerlin** [comment]
still doesn't work 
![image](https://user-images.githubusercontent.com/1460479/94855390-1f504a00-0437-11eb-94f1-d6d453d25579.png)

.prettierrc
"breakBeforeElse": true

.eslintrc.js
    'brace-style': [
      'error',
      'stroustrup',
      {
        'allowSingleLine': true
      }
    ],

**Comment by rom5jp** [comment]
The same problem still occurs here, even with the suggested configurations...

Any further ideas of how to solve this issue?

![image](https://user-images.githubusercontent.com/638656/157117083-a4340bcd-f849-4113-93c3-09137bf28bb0.png)
![image](https://user-images.githubusercontent.com/638656/157117278-c17af100-ce20-4d8e-a206-533d93fc37c5.png)
![image](https://user-images.githubusercontent.com/638656/157117284-a8ca6d51-99a1-4cba-b37a-28033d602ba3.png)

**Comment by ItsCubeTime** [comment]
Could we see this being added? What solution to other people use for this? Would like to have simple allman case formatting

**Comment by JounQin** [comment]
This is no such option for prettier at all.

https://github.com/prettier/prettier/issues/840

**Comment by ocsoares** [comment]
any solution?

**Comment by ony3000** [comment]
Hello everyone!

Today I released a [prettier plugin](https://www.npmjs.com/package/prettier-plugin-brace-style), maybe this will help.

**Comment by dockleryxk** [comment]
@ony3000 I was about to write my own plugin, how convenient

**Comment by xNevrroXx** [comment]
> Hello everyone!
> 
> Today I released a [prettier plugin](https://www.npmjs.com/package/prettier-plugin-brace-style), maybe this will help.

Thanks a lot)

**Comment by mmorgan4x** [comment]
@ony3000 does the plugin support the option for `allowSingleLine": true ` as well? If not can it?

**Comment by JounQin** [comment]
No idea What's your meaning, it's a 7 years old issue. 😆

**Comment by ony3000** [comment]
@mmorgan4x When I first created the plugin, it reflected my tastes a bit; I dislike single-line blocks, so I didn't implement the `allowSingleLine` option. :joy:

Now that I think about it again, it is very difficult to implement considering the internal logic of the current plugin.

@JounQin We talked about the prettier plugin I created. Please refer to [this comment](https://github.com/prettier/eslint-config-prettier/issues/26#issuecomment-1597289279). :laughing:

**Comment by max-programming** [comment]
I hated the `1tbs` style
@ony3000 You're a life saver buddy! Thanks!
