### ISSUE TITLE
max-statements-per-line

### ISSUE THREAD

**Issue by Zamiell** [prettier/eslint-config-prettier#262]
Should `max-statements-per-line` be included in the config?
Prettier does seem to put each statement on a new line. For example, see [this Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwAQCMsDc2GO+AXgQDpQCWAZtgBSRQAmNMN0AlNsHlmwBebAEYiAX2p0IORiWw1h2AAxElAHmwAbBAHMYACyIBqEzV798OEeOxSoAZwDuHMIabtHYTDQC2NFDosJbYrHB06ACu2jBIeJhw6ADWktJRUGCc0NgyEIyh1sp2Dgp5ynQZWVxQuRD5hYK2klRQjJWZ2bV5BXwCNmKS3AWtIAA0IBAADl2OyKBYmBDOAApYCHMo6NrO6ACecxO4mOhgyXAwAMrofnAAMoFwyJHajnBHJ2cXl1OngXrIGCYKLvEBvAKA4Ggxz-XQARSiEHgz22bwmACtHAAPS6wuAIpFPJAvNEgACOiPgKyWU02IHQjgAtFA4HBwqxxiAgegaNp-gBhCB+PzoZD07TaTkwqB6XQAQRgQJouCiVLgmAeLJRr1Bhhgfm0AHVDBw4I5fmA4JcNhwaKgOHsxWBHIc0CCAJJsBBXHw0GZytiXGB7XTa0lTJZvQ0nKZiiNm9WoJ4TQJvTAwanoPQisOg36YNNi-C4OCSiYRwIwQ00VhGZAADhUE0SFJoiUz2dFxNRoJg6Fw1drhmQACYJlE3gAVfubEmguB+Eusdl3YJ6KJZuAAMVkIsV-zF0RgEBAEgkQA).

**Comment by lydell** [comment]
Looking at https://eslint.org/docs/latest/rules/max-statements-per-line, it does indeed look unnecessary with Prettier! 👍

**Comment by Zamiell** [comment]
Do you want me to submit a PR?

**Comment by lydell** [comment]
Yes, that would be nice!

**Comment by lydell** [comment]
Thank you! Released in v8.10.0.
