### ISSUE TITLE
Definition for rule 'prettier/prettier' was not found

### ISSUE THREAD

**Issue by 6XGate** [prettier/eslint-config-prettier#266]
The documentation does not give instructions on properly installing this configuration. It will results in `Definition for rule 'prettier/prettier' was not found`. It needs to tell the dev to install the prettier plug-in AND add it to the plug-in list.

**Comment by lydell** [comment]
Hi! Can you provide steps to reproduce this issue, please? eslint-plugin-prettier is _not_ required for this config to be used.

**Comment by 6XGate** [comment]
Just installed the config repo add extended the shareable config.
1. `yarn add --dev eslint-plugin-prettier`
2. Add the `prettier` to the `extends` array.

**Comment by lydell** [comment]
eslint-<strong>config</strong>-prettier is this repo. It’s a config that turns a bunch of rules off.

eslint-<strong>plugin</strong>-prettier is the repo over here: https://github.com/prettier/eslint-plugin-prettier. It’s a plugin that provides the `prettier/prettier` rule.

**Comment by 6XGate** [comment]
sorry, put the wrong name in the list... it was support to be `yarn add eslint-config-prettier`.

**Comment by lydell** [comment]
I claim that it works.

Can you post _full_ steps to reproduce to prove what happens?

**Comment by lydell** [comment]
Closing due to no response.

**Comment by 6XGate** [comment]
Just got back on here, but the full setup is in a code base that I don't own and I never got an example working.
