### ISSUE TITLE
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information. Most configuration-related issues can only be resolved by [providing a full repro](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo). **If you don't provide a sample to reproduce your issue, your bug will most likely be closed.**

### ISSUE THREAD

**Issue by hmcmann65** [prettier/eslint-config-prettier#274]
This bug is missing information needed to diagnose the problem. Please see our [guide on how to open a good issue](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue) and provide the missing information. Most configuration-related issues can only be resolved by [providing a full repro](https://github.com/prettier/prettier-vscode/wiki/Writing-a-Good-Issue#5-provide-a-sample-github-repo). **If you don't provide a sample to reproduce your issue, your bug will most likely be closed.**

_Originally posted by @github-actions[bot] in https://github.com/prettier/prettier-vscode/issues/3200#issuecomment-1820212591_

**Comment by JounQin** [comment]
Reproduction please, and short and clean title and description.
