### ISSUE TITLE
[meta] maintenance question

### ISSUE THREAD

**Issue by JounQin** [prettier/eslint-config-prettier#275]
According to https://github.com/prettier/prettier-eslint/issues/949#issuecomment-1863321941, I'd like to take over to maintain this repo actively, questions:

1. Can you give me the owner role of this repository?
2. Can you give me the npm owner permission? My npm account is `jounqin`
3. I'd like to migrate the deveop and release workflow to `changesets` if I have the correct permission, will you reject such changes?
4. I'll add the funding section mentioned as the above issue, do you reject such changes?

**Comment by lydell** [comment]
1. I don’t seem to have permission to do so.
2. You have now been invited.
3. and 4. Feel free to make whatever changes you feel are improving the way maintainers work on the package, and how users are using the package. (For example, the testing setup is overdue some simplification.)

**Comment by JounQin** [comment]
@fisker @sosukesuzuki Would you like to help us? See also https://github.com/prettier/eslint-plugin-prettier/pull/624#issuecomment-1868064833

**Comment by fisker** [comment]
I'm on vacation. I'll find time to make the change.

**Comment by fisker** [comment]
Added @lydell and @JounQin  as "Admin" of this repo.  Anything else to do?

**Comment by JounQin** [comment]
Thanks @fisker!
