### ISSUE TITLE
The new `function-paren-newline` may conflict with Prettier

### ISSUE THREAD

**Issue by alexilyaev** [prettier/eslint-config-prettier#28]
ESLint 4.6.0 added `function-paren-newline`:  
https://eslint.org/blog/2017/09/eslint-v4.6.0-released

**Comment by alexilyaev** [comment]
Oops, forgot to bump the version before checking, it's all good, and I see it's in the changelog:  
https://github.com/prettier/eslint-config-prettier/blob/master/CHANGELOG.md#version-240-2017-09-02

**Comment by yspreen** [comment]
I'm confused. I'm not overriding any function paren newline in my project and still eslint and prettier are fighting each other. prettier fixes it in a way that eslint marks as an error. I had to disable the rule in eslint... but this issue reads like there should be a better way? @alexilyaev

**Comment by lydell** [comment]
You can use the [CLI helper tool](https://github.com/prettier/eslint-config-prettier#cli-helper-tool) to find problematic rules in your config.

**Comment by yspreen** [comment]
@lydell that's it! thanks a lot for the help here
