### ISSUE TITLE
conflicts with standard/computed-property-even-spacing

### ISSUE THREAD

**Issue by pekeler** [prettier/eslint-config-prettier#29]
I'm using eslint-config-prettier together with eslint-config-prettier-standard which works great except for this:

prettier wants
```js
    const { whatever } = loooooooooooooooooooooooong[
      something
    ].some.thiiiiiiiiiiiiing[0]
```

while standard wants
```js
    const { whatever } = loooooooooooooooooooooooong[something].some.thiiiiiiiiiiiiing[0]
```

I wonder if this is due to computed-property-even-spacing not being turned off.

`eslint-config-prettier-check` reports "No rules that are unnecessary or conflict with Prettier were found."

**Comment by lydell** [comment]
I use Prettier + eslint-config-standard + eslint-config-prettier in a pretty large project and haven't bumped into any problems yet. But it depends on what way you write your code too. Either way, eslint-config-prettier has no support for `standard` rules right now (only code ESLint, eslint-plugin-react and eslint-plugin-flowtype).

Could you make a gist or repo which I can clone and run `npm install && npm test` to see the problem? Then we can proceed with adding support for `standard` rules that conflict.

**Comment by pekeler** [comment]
@lydell I just created this repo to demonstrate the problem: https://github.com/pekeler/lint-problem.

**Comment by lydell** [comment]
Thanks, that helped a lot!

eslint-config-prettier 2.5.0 now has support for eslint-plugin-standard.

**Comment by pekeler** [comment]
Works - thank you very much!

**Comment by franleplant** [comment]
Im still seeing issues with `eslint-config-prettier` version `2.9.0`

**Comment by lydell** [comment]
@franleplant Can you make a VR app that let's me see through your eyes? :)

**Comment by franleplant** [comment]
@lydell sorry for being vague.

It's kind of hard for me to isolate the problem into a repo (Im working on a big app), maybe later on the week I can allocate some time to do it but the basic scenario is this:

```javascript
"eslint-config-prettier": "2.9.0",
"prettier": "1.10.2",
```

And Im using `eslint` and `eslint-config-standard`.

BTW I am working on a very messy code base.


This is the error I get from eslint:

```
 {line}:23  error    Expected "[" and "]" to be on the same line  standard/computed-property-even-spacing
```

And this is the prettier formatted offending code (it's nested inside JSX and inside other ternary expressions):

```javascript
                     {this.props.config.something &&
                      this.props.config.something[
                        'super_long_property_name'
                      ] ? (
                        <SomeComponent />
                      ) : (
                       <SomeOtherComponent />
                      )}

```

It looks related to long lines and breaking inside `[` and `]`.

I will try to make a reproducing repo soon

**Comment by franleplant** [comment]
And BTW the way I solved this was to add to my `.eslintrc` this rule override

```
"standard/computed-property-even-spacing": 0
```

And for now that works

**Comment by lydell** [comment]
Thanks!

That rule is already turned off:
https://github.com/prettier/eslint-config-prettier/blob/0f131661f718e278ec1e51529f56450a61f10b11/standard.js#L6

So it's strange that you had to turn it off manually. Perhaps you forgot to enable standard support?

```js
{
  "extends": [
    "standard",
    "prettier",
    "prettier/standard" // Perhaps you forgot this line?
  ],
  "plugins": [
    "standard"
  ],
```

**Comment by franleplant** [comment]
Oh, I didn't knew that, that's probably it, thanks a lot!!!

**Comment by franleplant** [comment]
Can confirm that that configuration fixes the described problems, thanks a
lot! (Sorry for being vague at the beginning again)

**Comment by corysimmons** [comment]
**Tip:** Don't include `prettier` in `extends` array. Just `prettier/standard` to disable Standard rules that directly conflict with Prettier ([not much](https://github.com/prettier/eslint-config-prettier/blob/195838648f9453ad962c91f5370eb023fedf70ec/standard.js)).

This way you get as much Standard and as little Prettier as possible.

**Comment by corysimmons** [comment]
Packages keep getting updated and Standard/eslint/Prettier/editor-plugins have turned into a huge headache to get working together, so I just uninstalled all that crap and just use VSCode's default Prettier integration for generic code style rules.

Now I actually get work done and products launched.

**Comment by the21st** [comment]
This surfaced for me with:
    eslint-config-prettier @ 6.7.0
    eslint-plugin-prettier @ 3.1.2
    prettier @ 1.19.1

My `.eslintrc.json`:

```json
{
  "env": {
    "browser": true,
    "es6": true,
    "node": true
  },
  "extends": [
    "standard",
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "plugin:security/recommended",
    "plugin:jest/recommended",
    "plugin:prettier/recommended",
    "prettier",
    "prettier/@typescript-eslint",
    "prettier/react",
    "prettier/standard"
  ],
  "plugins": [
    "react",
    "import",
    "node",
    "promise",
    "prettier",
    "standard",
    "security",
    "jest",
    "react-hooks",
    "@typescript-eslint",
    "@typescript-eslint/tslint"
  ]
},
...
```
