### ISSUE TITLE
TypeError for rule "@typescript-eslint/brace-style"

### ISSUE THREAD

**Issue by magelan1180** [prettier/eslint-config-prettier#293]
I have updated eslint-config-prettier to 9.1.0 together with eslint to 9.12.0

now i get the following TypeError: `TypeError: Key "rules": Key "@typescript-eslint/brace-style": Could not find "brace-style" in plugin "@typescript-eslint". Did you mean "@/brace-style"`

Some research on my project shows the use of this rule in eslint-config-prettier node package.

Checking https://eslint.org/docs/latest/rules/brace-style shows that this rule is deprecated since v8.53.0 and moved to [@stylistic/eslint-plugin-js](https://eslint.style/packages/js) (this is related to issue #283 i think, not sure if my issue should be closed as duplicate then)

**Comment by JounQin** [comment]
We even didn't provide any TypeScript declaration files directly.
