### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by protoEvangelion** [prettier/eslint-config-prettier#40]
In the `extends` array, if I write it like this

```json
    "extends": [
        "eslint:recommended",
        "prettier"
    ],
```

This error shows up: `Cannot convert undefined or null to object Referenced from: **/.eslintrc`

However when I write it like this: 

```json
    "extends": [
        "eslint:recommended",
        "plugin:prettier"
    ],
```

it works fine. Is that valid syntax or will that prevent it from working properly? Thanks!

**Comment by lydell** [comment]
First off, ESLint is giving you a very bad error message. Might be worth opening an ESLint issue about that.

Secondly, as far as I know the `plugin:foo` syntax is used when an ESLint _plugin_ also provides a _config._ This repo is just a config, not a plugin. Are you confusing this with the [recommended configuration of eslint-<strong>plugin</strong>-prettier](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration)? Are you sure that you have installed eslint-<strong>config</strong>-prettier?

I think that there’s nothing wrong in this repo, but that you have some general ESLint plugin/config usage problems.

**Comment by protoEvangelion** [comment]
@lydell Thanks for the quick response and clarification!

I ended up with this configuration and the error is not showing up anymore:

```json
 "parser": "babel-eslint",
 "extends": [
     "eslint:recommended",
     "prettier"
 ],
 "plugins": [
     "prettier"
 ],
```

Thanks for the great work!

**Comment by lydell** [comment]
Nice, glad you solved it! 👍
