### ISSUE TITLE
Configuration regarding trailing commas isn't respected

### ISSUE THREAD

**Issue by Haroenv** [prettier/eslint-config-prettier#41]
I seem to have an infinite loop of "please add commas", "please remove commas"

https://travis-ci.org/emotion-js/emotion/builds/326929845?utm_source=github_status&utm_medium=notification

https://github.com/emotion-js/emotion/pull/526

Any idea what could be the cause here? 

There don't seem to be any obvious changes regarding this recently though 🙃

**Comment by lydell** [comment]
I cloned that repo, ran `yarn` and then `yarn lint:check` and it reported no problems. What are you up to?

**Comment by Haroenv** [comment]
so weird 🤔 it might be my setup somehow, @tkh44 also can't replicate it

**Comment by Haroenv** [comment]
It was my vscode setup somehow I think, I misread the travis output

**Comment by lydell** [comment]
Glad you solved it! 🎉
