### ISSUE TITLE
eslint rule contradiction with prettier

### ISSUE THREAD

**Issue by fehergeri13** [prettier/eslint-config-prettier#47]
When I write this code: 
```
const { caretPosition: [selectionStart, selectionEnd] } = this.state;
```
the prettier reformats it to 
```
const {
  caretPosition: [selectionStart, selectionEnd]
} = this.state;
```

[live demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwhtjsADpQ44AW6UAJqnAJJQAOArjAGIRguuALw44ANwQwcwgHzkqNGpCiZpwHGHQAnODAAKETAEsYx6EhwBtTHBZgz0AMowdMADQ5b9x1ACiTAC6OAC+MjgwtMaYAHRq6PAA3IqhyVAhIO4gEBy+mMigOtoQAO76Ogj5KOjiEMaMmSAARtroYADWek4cbcZQAObIMNpccFl9ttoGrf0AtujIAGboqLZZAFaYAB4AQq0dXeizcAAyfXBLK2sgPdqTyM3oTQSo0I0c2n0wAOr1kcgADgADFkPkY4N9WhwHh84JNJI1dABHLjGXT6GbzS6rMYgWyzYxDEa4kwDFgARS4EHg2Ouriav0Y-yQACYssN0MZUH1+kQILMsSgoNALlkhHAACpPKrLHEhEJAA)

But the eslint wants it to be a single line.

![image](https://user-images.githubusercontent.com/7180398/43885724-f17c02be-9bb9-11e8-9906-020111fd87d1.png)

![image](https://user-images.githubusercontent.com/7180398/43885752-0f30cc18-9bba-11e8-8e72-4b95ab1bae43.png)

package.json
```
...
    "babel-eslint": "^7.2.3",
...
    "eslint": "^4.13.1",
    "eslint-config-prettier": "^2.9.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-prettier": "^2.4.0",
    "eslint-plugin-react": "^7.5.1",
...
    "prettier": "^1.9.2",

```

**Comment by lydell** [comment]
Hi! I’m sorry, but I don’t really understand your problem. You seem to be running Prettier through ESLint via eslint-plugin-prettier? So `eslint --fix` should do what you want?

Could you make an example repo that demonstrates your issue?

**Comment by fehergeri13** [comment]
Upgrading the dependencies fixed the issue
