### ISSUE TITLE
Use with create-react-app

### ISSUE THREAD

**Issue by bschwartz757** [prettier/eslint-config-prettier#49]
Hello,

I think this is a great project - been trying to get a handle on using prettier with eslint. I was already using the Prettier extension in my project, and found the default formatting to work well. I came across [this article on Medium](https://medium.com/technical-credit/using-prettier-with-vs-code-and-create-react-app-67c2449b9d08) and ended up looking into your plugin more closely, it seemed like a great way to manage everything. 

Unfortunately, when I added this package along with eslint-plugin-react and eslint-plugin-standard (and the example .eslintrc from eslint-config-prettier's README) to my existing create-react-app project, my JSX code went from this: 
```
        }) => (
          <Form
            id={this.state.requiredFieldsProps.formId}
            onSubmit={handleSubmit}
          >
            <Row>
              <Col xs="12" sm="6">
                <FormGroup>
                  <Label for={this.state.requiredFieldsProps.fields.lob.name}>
                    Foo
                  </Label>
                  <Field
                    component={Select}
                    name={this.state.requiredFieldsProps.fields.lob.name}
                    id={this.state.requiredFieldsProps.fields.lob.name}
                    change={handleChange}
                    value={values.lob}
                    options={requiredFieldsDropdowns.lob.options}
                  />
```
to this:
```
        }) => ( <
          Form id = {
            this.state.requiredFieldsProps.formId
          }
          onSubmit = {
            handleSubmit
          } >
          <
          Row >
          <
          Col xs = "12"
          sm = "6" >
          <
          FormGroup >
          <
          Label
          for = {
            this.state.requiredFieldsProps.fields.lob.name
          } > {
            this.state.requiredFieldsProps.fields.lob.label
          } <
          /Label> <
          Field component = {
            Select
          }
          name = {
            this.state.requiredFieldsProps.fields.lob.name
          }
          id = {
            this.state.requiredFieldsProps.fields.lob.name
          }
          change = {
            this.handleSelectChange
          }
          value = {
            values.lob
          }
          options = { 
            this.state.requiredFieldsDropdowns.lob
          }
          /> <
```
Obviously, this isn't very readable and actually causes linter errors. What's really odd to me is that prior to adding these packages, I was just using the prettier extension with no modifications and it was formatting my JSX nicely, as well as handling indentation and semicolons, etc. 
I tried adding a .prettierrc with settings like: 
```
{ "useTabs": false, "printWidth": 80, "tabWidth": 2, "singleQuote": true, "trailingComma": "none", "jsxBracketSameLine": false }
```
but that didn't seem to help.
I'm guessing that CRA has some default eslint config that it's trying to apply which conflicts with the settings Prettier and the packages/plugins I've installed are conflicting with. Any ideas on how I might get this all to work together? I'm trying to come up with a flexible, simple linter setup that can be used on a project with several developers using different code editors and this seems like a really promising solution, if I can work out the kinks.

Thanks!

**Comment by lydell** [comment]
Hi!

It's really hard to tell what's going on here from the information you provided. Here's some random advice:

- The article you linked to does not mention eslint-<strong>config</strong>-prettier at all. It does mention [eslint-<strong>plugin</strong>-prettier](https://github.com/prettier/eslint-plugin-prettier) though.
- Have you read [CRA's own documentation about using Prettier](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#formatting-code-automatically)?
- [CRA's ESLint config already contains eslint-plugin-react](https://github.com/facebook/create-react-app/blob/ca5998326deebf79845ca00f616b8dad11d90509/packages/eslint-config-react-app/index.js#L90)
- You won't gain much (if anything) by adding [standard](https://standardjs.com/).
- Could you make a demo repo that reproduces the problem? That helps debugging tremendously. Also, in the process of doing so there's a high chance you'll find the problem yourself.

**Comment by lydell** [comment]
Also, scrolling through the [ESLint rules used by CRA](https://github.com/facebook/create-react-app/blob/master/packages/eslint-config-react-app/index.js) I don't see anything that would conflict with Prettier.

**Comment by bschwartz757** [comment]
@lydell Thanks! This looks like it should get me what I need. I hadn't found CRA's documentation on using prettier, looks like there's a well-established way of integrating. 

I'll close this, your input was extremely helpful. A mention of using this with CRA on your project's readme (maybe along with the link you shared above) may help future visitors. 

Thanks!
