### ISSUE TITLE
Conflict with import/newline-after-import

### ISSUE THREAD

**Issue by chris-verclytte** [prettier/eslint-config-prettier#50]
I am currently using prettier through eslint run and there is a (tricky) rule that seems to break.

I am using JS without semicolons which implies declaration of IIFE with a semicolon before parenthesis. Then I have the following case:
- Ok for prettier, not ok for eslint that will consider that first line is ending after the ";" and then eslint returns an "import/newline-after-import" error
```js
const EventStore = require('../service/eventStore')

;(async () => {
  const eventBus = await EventBus.getInstance()
  eventBus.stanConnection.on('connect', registerCommandHandlers)
})()
```

- Ok for eslint, not ok for prettier that returns a "Delete ↵" on line 3.
```js
const EventStore = require('../service/eventStore')
;

(async () => {
  const eventBus = await EventBus.getInstance()
  eventBus.stanConnection.on('connect', registerCommandHandlers)
})()
```

Could not find a suitable solution for this particular use case.

**Comment by lydell** [comment]
Hi! Thanks for the issue! Have you considered reporting this to eslint-plugin-import? I’m not sure it makes sense disabling this rule in eslint-config-prettier. It would be better to enhance the rule, I think.

**Comment by chris-verclytte** [comment]
Hi @lydell, thanks for the answer, you're definitely right. I transferred it [here](https://github.com/benmosher/eslint-plugin-import/issues/1169) for follow-up.
