### ISSUE TITLE
unicorn/number-literal-case conflict with Prettier

### ISSUE THREAD

**Issue by j0hnm4r5** [prettier/eslint-config-prettier#51]
[I'm pretty sure this issue goes here, and not with prettier/prettier-eslint, but please let me know otherwise]

When using both prettier/prettier-eslint and prettier-eslint-config-prettier, ESLint's Autofix-On-Save converts hex values to uppercase automatically, and then complains that they aren't lowercase, with e.g. ``Replace `FFFFFF` with `ffffff` (prettier/prettier)``.

Using ESLint VSCode Plugin, with `{ "eslint.autoFixOnSave": true }`, and the following configs:

`.eslintrc`

```
{
	"env": {
		"browser": true,
		"node": true
	},
	"extends": [
		"airbnb",
		"plugin:promise/recommended",
		"plugin:unicorn/recommended",
		"plugin:prettier/recommended",
		"prettier/react"
	],
	"plugins": ["import", "promise", "unicorn"],
	"rules": {
		"prettier/prettier": "error",
		"quotes": ["error", "backtick"],
		"no-console": "off",
		"no-plusplus": "off",
		"prefer-const": "error",
		"prefer-template": "error",
		"import/first": "off",
		"unicorn/filename-case": "off",
		"radix": "off",
		"import/prefer-default-export": "off",
		"no-use-before-define": "off",
		"no-underscore-dangle": "off",
		"class-methods-use-this": "off"
	}
}
```

`.prettierrc`

```
{
	"printWidth": 72,
	"tabWidth": 4,
	"useTabs": true,
	"semicolons": true,
	"singleQuote": false,
	"trailingComma": "es5",
	"bracketSpacing": true,
	"arrowParens": "always"
}
```

**Comment by lydell** [comment]
Hi! Could you put the .eslintrc and .prettierrc you pasted above into a reproduction repo, along with a package.json, some example code that fails, and what CLI commands to run to reproduce? That would help a lot.

**Comment by j0hnm4r5** [comment]
Here you go! https://github.com/j0hnm4r5/prettier-eslint-test

No CLI commands. Just use ESLint in VSCode, and see the errors in the Problems console there (and also as red underlines inline).

**Comment by lydell** [comment]
> Just use ESLint in VSCode

No, not "just". I don't have it installed, and don't feel like installing it at the moment. And, more importantly, the fewer layers the easier to debug. I would very much appreciate debugging from the CLI!

**Comment by j0hnm4r5** [comment]
Sorry about that! It still works the same with `eslint index.js`, and I've added a `npm test` alias script that does that.

**Comment by lydell** [comment]
Cool, thanks! Did you forget to push that to github? I can't find it here: https://github.com/j0hnm4r5/prettier-eslint-test/blob/203f94adb2f64645949ffe87cdea42cf83d6898c/package.json#L7

**Comment by j0hnm4r5** [comment]
I might have? Just tried again to be safe. Confirmed there now!

**Comment by lydell** [comment]
Awesome! Seems you like you forgot to install ESLint.

```
$ npm test

> prettier-example@1.0.0 test /home/lydell/stuff/prettier-eslint-test
> eslint index.js

sh: 1: eslint: not found
npm ERR! Test failed.  See above for more details.

$ grep '"eslint"' package.json; or echo 'no matches'
no matches
```

Could you install it and double-check that your repo actually works, please?

**Comment by j0hnm4r5** [comment]
Pushed and tested with the added dependency.

I was using a globally installed ESLint of the same version, but as that was using the local config files it didn't affect the issue.

**Comment by j0hnm4r5** [comment]
Awesome, thanks a ton! Hopefully this thread will be useful for people in the future.

Is there way to turn it off in Prettier? I actually prefer the `0xFFF` format to the `0xfff` one.

**Comment by lydell** [comment]
I prefer uppercase too, but there's no way to turn the lowercasing off in Prettier.
