### ISSUE TITLE
How to tell it not to accept TypeScript syntax in JavaScript files?

### ISSUE THREAD

**Issue by trusktr** [prettier/eslint-config-prettier#56]
I have some files that are not TypeScript, but Prettier has no problem formatting them. When I install eslint-config-prettier, ESLint also is not telling me about syntax errors on TypeScript syntax. I'd like for ESLint to tell me that any Type-related stuff is a syntax error in `js` or `jsx` files.

**Comment by trusktr** [comment]
Here's what it is doing (in Atom):

When I put `******` into the code, it has a syntax error as expected, but then only when I put a `(((((` into the code does it ignore that and tell me that `interface` is a reserved word:

![example](https://user-images.githubusercontent.com/297678/46904130-67fe4980-ce94-11e8-8242-c0263c239f2d.gif)

**Comment by trusktr** [comment]
eslintrc:

```js
module.exports = {
	extends: ['prettier'],
	parser: 'babel-eslint',
}
```

**Comment by j-f1** [comment]
My guess is that it’s being passed as Flow. In both Flow and TypeScript, interfaces are statements so they can’t be wrapped in parentheses. There isn’t a syntax error for the parens themselves because the parser hasn’t gotten far enough to determine that there are no matching closing parens when it finds the other error.

**Comment by trusktr** [comment]
How to tell it not to accept TypeScript syntax in JavaScript files?

**Comment by lydell** [comment]
That’s ESLint’s job.

**Comment by trusktr** [comment]
@lydell I was thinking it was Prettier's because the only thing I have in my `eslintrc` is

```js
	extends: ['prettier'],
```

So the option is not inside Prettier's config?

And I thought ESLint came with no rules, so how would it be ESLint's job if it comes with no rules and the only ones I have are Prettier's?

**Comment by trusktr** [comment]
Obviously Prettier understands the type syntax (otherwise formatting wouldn't work) so it would make sense to be able to tell Prettier not to accept type format in any `.js` or `.jsx` files, and for this to be configurable in Prettier's ESLint config.

**Comment by trusktr** [comment]
After all, I'm not trying to use ESLint specifically, I'm trying to use Prettier, and I just want my editor to otherwise tell me I have syntax errors in JS files, so it seems like this is a Prettier concern.

**Comment by trusktr** [comment]
Hmmm, well, changed my `eslintrc` to

```js
module.exports = {
	// extends: ['prettier'],
	parser: 'babel-eslint',
}
```

and the behavior seems to be exactly the same. (darn)

So maybe it currently isn't a Prettier concern, but maybe it would be nice if it was.

**Comment by trusktr** [comment]
If I avoid using decorators (because ESLint doesn't support them out of the box), then I can solve this problem by using the following `eslintrc` config:

```js
module.exports = {
	parserOptions: {
		sourceType: 'module',
		ecmaVersion: 2018,
	},
}
```

I now get syntax errors on type annotations. Yaaaaaaaaaay.

So, what's the point of `eslint-config-prettier` then?

**Comment by trusktr** [comment]
> That’s ESLint’s job, not Prettier’s.

I guess you don't think about your user experience. I am here not because of ESLint, but because of Prettier.

**Comment by lydell** [comment]
I didn’t have the energy to read all your comments, so I’m just going to answer this:

> I thought ESLint came with no rules

By default, the only thing ESLint does is checking your code for syntax errors (since it parses your code). ESLint needs to be configured for the syntax features you want to use.

Prettier is not a syntax checker. It tries to support as much as possible out of the box.

**Comment by j-f1** [comment]
Also, Flow files use the `.js` extension too.

**Comment by lydell** [comment]
Hmm, yes, when I think about it that might be the case. I have a vague memory of not getting syntax errors in my editor (which uses ESLint) but syntax errors from webpack (where I use Babel) when copy-pasting some code from a Flow project to a non-Flow project. But that’s a babel-eslint issue. There’s also this rule in case it helps: https://eslint.org/docs/rules/no-restricted-syntax

**Comment by trusktr** [comment]
> no-restricted-syntax

Ah, thanks! That's a good rule to know. I think that will definitely help.
