### ISSUE TITLE
Disable react/jsx-indent

### ISSUE THREAD

**Issue by julien-f** [prettier/eslint-config-prettier#65]
Rule provided by [eslint-plugin-react](https://github.com/yannickcr/eslint-plugin-react#jsx-specific-rules) used by [eslint-config-standard](https://github.com/standard/eslint-config-standard).

**Comment by lydell** [comment]
Hi! That rule is already included:

https://github.com/prettier/eslint-config-prettier/blob/152bd7d6582816a493ac0ab619bd8789ac57f280/react.js#L11

Perhaps you forgot to put `"prettier/react"` in the `extends` array of your .eslintrc?

**Comment by julien-f** [comment]
Indeed! :confounded: 

Sorry for this and thanks for the prompt answer :slightly_smiling_face:

**Comment by MisterEmpyrean** [comment]
> Hi! That rule is already included:
> 
> https://github.com/prettier/eslint-config-prettier/blob/152bd7d6582816a493ac0ab619bd8789ac57f280/react.js#L11
> 
> Perhaps you forgot to put `"prettier/react"` in the `extends` array of your .eslintrc?

Bingo, forgot to add that rule inheritance. Good man!
