### ISSUE TITLE
semi error in Vue Template

### ISSUE THREAD

**Issue by zlxbuzz** [prettier/eslint-config-prettier#66]
#### eslint-config-prettier 3.3.0
I use vim-prettier will generate semi automatically , but cause error ,how do I configure it? 
#### Input:
```vue
<com @click="$emit('click');"></comp>
```

#### Output:
```bash
error  Delete `;`  prettier/prettier
```

#### Expected behavior:
No error;

**Comment by lydell** [comment]
How am I supposed to reproduce this? I don’t have enough information to help you.

**Comment by zlxbuzz** [comment]
@lydell Thanks for respond to my question, i just want to disallows this rule(semi) in vue.template , not in *.js or vue.script.Is there any way?

#### My config
```js
 module.exports = {
    env: {
      browser: true,
      es6: true,
      commonjs: true
    },
    parserOptions: {
      sourceType: "module"
    },
    extends: [ "plugin:vue/base","plugin:prettier/recommended"]
  };
```

**Comment by zlxbuzz** [comment]
@lydell  I have a little thought, thank you for your reply.
