### ISSUE TITLE
Add config for disabling eslint-plugin-babel rules

### ISSUE THREAD

**Issue by silvenon** [prettier/eslint-config-prettier#67]
[`eslint-plugin-babel`](https://github.com/babel/eslint-plugin-babel) contains rules that conflict with Prettier, so it might be a good idea to add another ESLint config called `prettier/babel`. This seems easy, so I might be able to submit a PR for this.

**Comment by lydell** [comment]
Feel free to send a PR! :+1:

**Comment by lydell** [comment]
Is there a config that enables the conflicting rules somewhere? Otherwise I’m not sure there’s any point adding them to eslint-config-prettier.

**Comment by silvenon** [comment]
Maybe there's going to be a set of recommended rules through `plugin:babel/recommended` (I don't think there currently is one), but companies often create internal configs, so that's when having the disabling Prettier config would useful.

Any file can act as a config, it doesn't even have to be a package.

I'll send a PR. 😄

**Comment by lydell** [comment]
I see. Go ahead making a PR, then, if you feel like it! :+1:

**Comment by lydell** [comment]
Released in v3.6.0.
