### ISSUE TITLE
Add support for typescript-eslint

### ISSUE THREAD

**Issue by brimtown** [prettier/eslint-config-prettier#77]
ESLint [recently announced](https://eslint.org/blog/2019/01/future-typescript-eslint) that `eslint-plugin-typescript` would be moving to [`typescript-eslint`](https://github.com/typescript-eslint/typescript-eslint).

When starting a project with the new `typescript-eslint` and `eslint-config-prettier`, `eslint-config-prettier` does not disable styling rules in `typescript-eslint`. It seems like this because the scopes in [typescript.js](https://github.com/prettier/eslint-config-prettier/blob/master/typescript.js#L5-L7) need to be updated from `typescript/` to `@typescript-eslint/`.

Happy to send a PR over doing that myself if this would suffice!

**Comment by brimtown** [comment]
Just saw https://github.com/prettier/eslint-config-prettier/pull/74 was merged, nevermind! Looking forward to the release 😄

**Comment by lydell** [comment]
v4.0.0 is now released!
