### ISSUE TITLE
Conflict with @typescript-eslint/eslint-plugin

### ISSUE THREAD

**Issue by denysdovhan** [prettier/eslint-config-prettier#80]
You probably know about [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint) project. The problem is that Prettier rules are conflicting with those from typescript. 

As I understand, this config just disables all rules that possibly conflict with Prettier rules. I'd be happy to open a PR with a fix (disable all conflicting `typescript-eslint` rules).

Will you consider this solution or you have other ideas regarding this issue?

**Comment by lydell** [comment]
typescript-eslint is already supported. Maybe you forgot to add `"prettier/@typescript-eslint"` to your `"extends"` array?

**Comment by denysdovhan** [comment]
Thanks! My bad. Sorry for bothering 🙏
