### ISSUE TITLE
If i am extending airbnb config and I use react, do i need to add prettier/react ?

### ISSUE THREAD

**Issue by gaurav5430** [prettier/eslint-config-prettier#82]
I am finding it difficult to understand the supported plugins section in README

In my eslint config for a react project I am using 
`extends: ["airbnb", "prettier"],
  plugins: ["prettier"],`

when do i need to add `prettier/react` in extends ?

**Comment by lydell** [comment]
Yes! eslint-config-airbnb enables eslint-plugin-react rules, so you need `prettier/react`. Basically, if you have `eslint-plugin-foo` in your package.json, you need `prettier/foo` (if it exists).

Do you have any suggestions on how to make this clearer?

**Comment by gaurav5430** [comment]
Adding this would help:
> Basically, if you have `eslint-plugin-foo` in your package.json, you need `prettier/foo` (if it exists).

Or

maybe something like "If you extend a config which uses a plugin, it is recommended to use prettier/that-plugin" followed by a few examples.

**Comment by Abobos** [comment]
Why is it recommended to use prettier/that-plugin
