### ISSUE TITLE
Disable react/self-closing-comp

### ISSUE THREAD

**Issue by gaurav5430** [prettier/eslint-config-prettier#83]
The current exclusion config for `react` seems to turn off a handful of jsx related rules.
How do you decide which rules to turn off?

Is the` react/self-closing-comp` rule a style related rule, should it be part of prettier exclusions?

Prettier seems to automatically correct this when saving, but while working on the file in the editor, i get 2 linting errors, one from `prettier` and another from `airbnb config`.

Please help me understand whether or not this is something that should be turned off by `eslint-config-prettier`?
(I am still trying to understand what to expect from prettier and eslint-config-prettier)

**Comment by lydell** [comment]
Good point, we should add this one.

**Comment by gaurav5430** [comment]
It seems like a small change, would you accept a PR for it ?

**Comment by lydell** [comment]
Released in v4.1.0.
