### ISSUE TITLE
Should `unicorn/prevent-abbreviations` be turned off?

### ISSUE THREAD

**Issue by ehmicky** [prettier/eslint-config-prettier#89]
[`unicorn/prevent-abbreviations`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prevent-abbreviations.md) is turned off.

How is that rule incompatible with Prettier?

**Comment by lydell** [comment]
It's just turned off for the linting of the source code of this project itself :)

It's not listed in https://github.com/prettier/eslint-config-prettier/blob/master/unicorn.js

**Comment by ehmicky** [comment]
Oh I see :) Thanks for the answer!
