### ISSUE TITLE
react/jsx-curly-newline should be disabled

### ISSUE THREAD

**Issue by ThiefMaster** [prettier/eslint-config-prettier#96]
eslint-plugin-react added this rule in 7.14.0 and it's incompatible with prettier styling.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-newline.md

**Comment by lydell** [comment]
Released in v5.1.0.

**Comment by ybiquitous** [comment]
@lydell Thank you very much! 👏

**Comment by PaulRBerg** [comment]
Using `^6.3.0` and still getting this error. Here's my React code:

```
<Frame
  onClick={() =>
    dispatch({ type: state.isWithdrawSidebarOpen ? "CLOSE_WITHDRAW_SIDEBAR" : "OPEN_WITHDRAW_SIDEBAR" })
  }
>
```

Eslint complains about the closing bracket `}`, but it's prettier who formats it like that.
